### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by joehua87** [joehua87/seo-audit#1]
## Not found
* [ ] Broken links
* [ ] Broken images

## Optimize
* [ ] Title
* [ ] Meta Description
* [ ] Image size is not optimized
* [ ] Image does not have alt

## Misc
* [ ] Get meta data (what Google see, what Facebook see, ...)
* [ ] Get PageSpeed score from Google
